name: Install, Build & Run Cypress

on: [push]

jobs:
  test:
    runs-on: macos-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - name: Install Packages
        run: yarn
      - name: Build
        run: yarn build
      - name: Run Cypress
        run: yarn test:e2e:ci
        env:
          CYPRESS_DASHBOARD_KEY: ${{ secrets.CYPRESS_DASHBOARD_KEY }}
