name: End-to-end tests
on:
  [push, pull_request]
jobs:
  build-app:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Build App
      run:  |
        yarn install
        yarn build
        yarn serve:test
  e2e-test:
    runs-on: ubuntu-latest
    needs: build-app
    steps:
    - name: Run Cypress
      env:
        CYPRESS_BASE_URL: 'http://localhost:5000/'
        CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_DASHBOARD_KEY }}
        CYPRESS_TEST_USER_EMAIL:  ${{ secrets.TEST_USER_EMAIL }}
        CYPRESS_TEST_USER_PASSWORD:  ${{ secrets.TEST_USER_PASSWORD }}
      run: yarn test:e2e:ci